export const refs = {
  spinner: document.querySelector('.js-spinner'),
  load: document.querySelector('[data-load]'),
  headerSearcherEl: document.querySelector('.header__searcher'),
  searchFormEl: document.querySelector('.header__form'),
  homeBtn: document.querySelector(['[data-action="home"]']),
  libraryBtn: document.querySelector('[data-action="library"]'),
  headerBtn: document.querySelector('.header__btn'),
  header: document.querySelector('.header'),
  headerNav: document.querySelector('.header__nav'),
  watchedBtn: document.querySelector('[data-action="watched"]'),
  queueBtn: document.querySelector('[data-action="queue"]'),
  moviesList: document.querySelector('.movie__list'),
  movieCard: document.querySelector('.movie__item'),
}
